name: API Contactos CI/CD

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_BASE_NAME: aminespinoza/apicontactos

jobs:
  API_Image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ApiContactos
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
        
      - name: Install az containerapp extension
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          
      - name: Build Docker NET image
        run: | 
          docker build --platform linux -t $IMAGE_BASE_NAME .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy image to hub
        run: |
          docker push $IMAGE_BASE_NAME:latest
          
      - name: Deploy Container App
        run: |
          az containerapp up --name contactosapi --image $IMAGE_BASE_NAME:latest --resource-group rg--warm-wren --environment devops-env --ingress external --target-port 8080
