name: API Contactos CD/CD

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_BASE_NAME: aminespinoza/apicontactos:latest

jobs:
  API_Image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ApiContactos
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Looking for files
        run: ls -a
        
      - name: Build Docker NET image
        run: | 
          docker build --platform linux --tag $IMAGE_BASE_NAME -f .
