name: Deploy infrastructure

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    env:
      ARM_CLIENT_ID: ${{secrets.CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TENANT_ID}}
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/infra
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1 

    - name: Terraform init
      id: init
      run: terraform init

    - name: Terraform validate
      id: validate
      run: terraform validate -no-color
      if: steps.init.outcome == 'success'

    - name: Terraform plan #Here is the state lock
      id: plan
      run: terraform plan -out plan.out
      if: steps.validate.outcome == 'success'

    - name: Terraform apply
      id: apply
      run: terraform apply "plan.out"
      if: steps.plan.outcome == 'success'
